CREATE DATABASE IF NOT EXISTS loja_drip
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

USE loja_drip;

CREATE TABLE IF NOT EXISTS usuarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    displayName VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    google_id VARCHAR(255) UNIQUE NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
